version: "3"
services:
  postgres:
    image: postgres:10.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=whatsapp